# Generated by Django 3.0.2 on 2020-01-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_heading', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=50)),
                ('post_publish_date', models.DateTimeField()),
                ('post_heading', models.CharField(default='', max_length=50)),
                ('post_sub_heading', models.CharField(default='', max_length=100)),
                ('post_body', models.TextField(default='')),
                ('post_link_of_destination_heading', models.CharField(default='', max_length=50)),
                ('post_img', models.ImageField(blank=True, default='', upload_to='blog/images')),
                ('post_url', models.CharField(max_length=50)),
                ('post_link_of_destination', models.ManyToManyField(to='blog.Url')),
            ],
        ),
    ]
