# Generated by Django 3.0.2 on 2020-02-01 11:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20200201_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish_date',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_heading',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_sub_heading',
            new_name='sub_heading',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_link_of_destination',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_link_of_destination_heading',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_publish_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_short_desc',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='Devraj', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 1, 11, 31, 50, 335002, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='slug', unique_for_date=models.DateTimeField(default=datetime.datetime(2020, 2, 1, 11, 31, 50, 335002, tzinfo=utc))),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=''),
        ),
    ]
